<a href="https://colab.research.google.com/github/Subhadeep-Paul/Python_World/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Chapter 1: NumPy Basics

In [ ]:
%%capture
!pip install numpy
print("This %%capture will not let anything to show as output")

In [2]:
import numpy as np
import time

Using Python list to iterate over each number and calculate the sum and average.

In [ ]:
numbers = [20 , 22, 24, 26, 28, 30]
sum = 0;
for i in numbers:
  sum = sum + i
print("The total sum is:" , sum)
print("The average of numbers is:" , int(sum/len(numbers)))

The total sum is: 150
The average of numbers is: 25


Now we will be taking help of the NumPy library, Calculation is fast and memory efficient.

In [ ]:
sum = np.array(numbers).sum()
print("The total sum is:" , sum)
print("The average of numbers is:" , int(np.average(numbers)))

The total sum is: 150
The average of numbers is: 25


###Creating arrays in NumPy from scratch.
Zeros & Ones functions available in NumPy.

In [ ]:
array_zero = np.zeros((2,3))
print ("Zeros array: \n" , array_zero)


array_ones = np.ones((3,2))
print ("Ones array: \n" ,array_ones)


array_random = np.random.random((3,3))
print ("Random array: \n" ,array_random)


array_full = np.full((5,5), 4)
print ("Full array: \n" ,array_full)

#Or you can create it by multiplying a specific value with the ones array
#But notice the difference of output with the similar full function array
array_full4 = 4 * np.ones((5,5))
print ("Full array: \n" ,array_full4)


array_sequence = np.arange(1, 50, 3)
print ("Sequence array: \n" , array_sequence)


array_identity = np.eye(5) #Shape = 5 means 5by5 matrix
print ("Identity array: \n" , array_identity)

Zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Random array: 
 [[0.14063968 0.26698013 0.21248006]
 [0.38377132 0.06681709 0.05618722]
 [0.42673065 0.98682126 0.39420603]]
Full array: 
 [[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
Full array: 
 [[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
Sequence array: 
 [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
Identity array: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Now we will look into multiplication of NumPy array vs Python List. Closely watch the observation.

In [ ]:
print ("Multiplication of python list: " , numbers * 2)
print ("Multiplication of NumPy array: " , np.array(numbers))

Multiplication of python list:  [20, 22, 24, 26, 28, 30, 20, 22, 24, 26, 28, 30]
Multiplication of NumPy array:  [20 22 24 26 28 30]


In the multiplication of python list, the array itself got doubled because of the multiplication factor of 2. BUT, incase of NumPy Array, the values present in the array got multiplicated. Now, we'll look into the time required to calculate within the list/numpy array.

In [3]:
start = time.time()
py_list = [i*2 for i in range(1,100000000)]
print ("Time taken by python list: " , (time.time() - start))

start = time.time()
numpy_array = np.arange(1,100000000) * 2
print ("Time taken by NumPy array: " , time.time() - start)

Time taken by python list:  10.526396036148071
Time taken by NumPy array:  0.8552436828613281


Notice the difference between the Python list and NumPy array. Python List have taken close to 11sec while the NumPy arrray have solved the same operation under 0.2 sec, which implies it is 50times faster than Python List.